repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest version available
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Matches your ruff version
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest --cov=src --cov-branch
        language: system
        pass_filenames: false
        always_run: true
